FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

ARG CACHE_DATE=not_a_date

WORKDIR /plk-microservice-product

COPY ./requirements.txt requirements.txt

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY ./app /app
